#define BUZZER 9
#define LDR1 14

long frequency;

// stores a multiplier value to determin the pitch of the sound
int pitch = 1;

// controls the speed of the change in sound
int tempo = 2;

// range of pitches available
int range = 100;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);

  // initial buzzer
  pinMode(BUZZER, OUTPUT);  
}

void loop() {
  // put your main code here, to run repeatedly:

  // determine tone to be generated by buzzer
  frequency = analogRead(LDR1) * pitch;

  // creates a range of accessible tones
  frequency = range * ((frequency + 50) / range);

  // generate sound
  tone(BUZZER, frequency);

  // tempo of instrument determined by the delay
  delay(tempo * 100);

  Serial.print("Frequency: ");
  Serial.println(frequency);
}
